- .craft.yml
- .github/workflows/merge-jobs.yml
- .github/workflows/release.yml
- README.md
- bin/bump-version.sh
- docs/conditional-script.md
- vite.config.ts
The CDN bundle for a JS SDK release is something like: https://browser.sentry-cdn.com/8.32.0/bundle.tracing.replay.min.js`
So for the toolbar is should be something like: `https://browser.sentry-cdn.com/sentry-toolbar/index.min.js`
> build: Setup Craft to deploy the toolbar into gcs & the CDN

- .env.example
- README.md
- src/env/demo/App.tsx
- src/lib/utils/ApiProxy.spec.ts
- src/lib/utils/ApiProxy.ts
Docs for .env files are: https://vite.dev/guide/env-and-mode
Now you can make your own `.env.local` file then restart the server. This makes it easier to point to different sentry api backends for testing different api responses.
> chore: Allow overriding default toolbar config with .env files

- src/lib/components/AppRouter.tsx
- src/lib/hooks/useClearQueryCacheOnProxyStateChange.ts
- src/lib/hooks/useNavigateOnProxyStateChange.ts
Before we were navigating to `'/'` after any proxyState change or nav, which meant you couldn't actually open up a panel.  Fixed with `if (match && unauthPaths.includes(match.pathname)) {`
> fix: Extract use*OnProxyStateChange hooks and fix Navigate conditions

- src/env/demo/App.tsx
- src/lib/components/AppRouter.tsx
- src/lib/components/unauth/Connecting.tsx
- src/lib/components/unauth/InvalidDomain.tsx
- src/lib/components/unauth/MissingProject.tsx
- src/lib/components/unauth/UnauthPill.tsx
- src/lib/context/ApiProxyContext.tsx
Login looks like this, passing through to the iframe:
And messages are looking like this so far:
> feat: Improve styles of unauth messages

- src/lib/sentryApi/urls.spec.ts
- src/lib/sentryApi/urls.ts
The comment in the code also says it... but the /iframe/ view is setting our cookie into an origin that includes the org-subdomain. so like `document.cookie = 'sid=123; domain=acme.sentry.io`
Therefore we don't have auth when we try to use a region-subdomain like `us.sentry.io` for the api calls.
The result is slower api calls because the server will need to sort out which region to use, and jump over to it. We can fix this in the future though.
> fix: Dont use region subdomain api origins

- src/lib/components/icon/IconLock.tsx
Same as in https://github.com/getsentry/sentry/pull/79938, which is the source of this icon file.
> ref: IconLock doesnt have a solid state

- mock/server/public/toolbar/iframe.html
- mock/server/public/toolbar/login-success.html
- src/lib/context/__mocks__/defaultConfig.ts
- src/lib/hooks/fetch/useSentryApi.ts
- src/lib/sentryApi/urls.spec.ts
- src/lib/sentryApi/urls.ts
- src/lib/utils/ApiProxy.spec.ts
- src/lib/utils/ApiProxy.ts
This is to keep templates up to date with https://github.com/getsentry/sentry/pull/80003 and also fix the urls so that we're using subdomains most of the time with sentry saas.
> fix: Explicitly ask for te non-subdomain origin when loading the toolbar login-sucess popup

- mock/server/public/toolbar/iframe.html
- src/lib/components/AppRouter.tsx
- src/lib/context/ApiProxyContext.tsx
The production templates are updated in https://github.com/getsentry/sentry/pull/80035 to align with this.
I think that if that production change doesn't land right away, this change will still be safe. The idea is that we are not by default... and now not ever showing the login form. `VISIBLE_IFRAME` is false by default, and now removed.
> ref: Remove unused form/button, prefer the request-authn command instead

- src/lib/components/datetime/RelativeDateTime.tsx
- src/lib/components/icon/SVGIconBase.tsx
- src/lib/components/panels/feedback/FeedbackListItem.tsx
- src/lib/components/panels/feedback/FeedbackPanel.tsx
- src/lib/components/panels/issues/IssueListItem.tsx
- src/lib/components/panels/issues/IssuesPanel.tsx
Adds some CSS and formatting stuff to make the issue and feedback panels look like the one on the Sentry toolbar
Issues Panel
Feedback Panel
Relates to https://github.com/getsentry/sentry-toolbar/issues/75
> feat(toolbar): Make Issue and Feedback Panels look like Sentry toolbar

- docs/conditional-script.md
- src/env/demo/App.tsx
- src/lib/components/AssignedTo.tsx
- src/lib/components/DebugState.tsx
- src/lib/components/Navigation.tsx
- src/lib/components/unauth/Login.tsx
- src/lib/context/ApiProxyContext.tsx
- src/lib/hooks/useSentryClientAndScope.ts
- src/lib/index.ts
- src/lib/types/config.ts
- src/lib/utils/ApiProxy.spec.ts
- src/lib/utils/ApiProxy.ts
The typedoc is the only documentation so far, and it says:
```
* You can set debugging to a comma-separated string containing
* different levels of debugging to enable.
*
* See `enum DebugTarget` for what specific targets are available.
* Include the target `all` to enable everything.
```
So if you have an `.env` file then you can set:
```filename=.env
VITE_SENTRY_TOOLBAR_DEBUG=logging,state
```
or 
```filename=.env
VITE_SENTRY_TOOLBAR_DEBUG=all
```
or
```filename=.env
VITE_SENTRY_TOOLBAR_DEBUG=
```
> feat: Update the granularity of debug info

- src/lib/hooks/useCurrentSentryTransactionName.ts
- src/lib/utils/transactionToSearchTerm.spec.ts
- src/lib/utils/transactionToSearchTerm.ts
I say 'better' `/` handling because we're:
- Not adding leading & trailing slashes anymore
- Still replacing multiple slashes, (ie: `//`) with `/` anywhere they appear.
Before we were adding trailing `/` which wasn't working for my test site which does not require a trailing `/` in the url, therefore searches for `/cart/` were not matching `/cart` in sentry.
> fix: Improve transaction name to search to support uuid, and better `/` handling

- src/lib/components/base/ExternalLink.tsx
- src/lib/components/panels/feedback/FeedbackListItem.tsx
- src/lib/components/panels/feedback/FeedbackPanel.tsx
- src/lib/components/panels/issues/IssueListItem.tsx
- src/lib/components/panels/issues/IssuesPanel.tsx
- src/lib/components/project/ProjectIcon.tsx
- src/lib/types/config.ts
Panel title looks like a link now & we have `<ProjectIcon>` next to each issue-id
> ref: Refactor fetching into ProjectIcon and improve ExternalLink css overriding

- src/lib/components/datetime/RelativeDateTime.tsx
Just have it auto-update the string `24min ago` to be `25min ago` if you've looking at the page for a while.
The update interval can be set manually to either `second`, `minute` or `hour` but if you don't set it then we'll see how old is the date, and set an interval that's appropriate. If the timestamp starts being really recent, then we'll update it every second, but if you keep the page open for hours and hour then we'll get a new value from getRecommendedInterval()` and slow down the updates because it won't be changing as often anyway.
I'm using `dangerouslySetInnerHTML` here to keep react away from the changing values. If i were mutating the children directly and react wanted to re-render it could be surprised that the value is not what it expected.
> feat: RelativeDateTime auto-updates the relative rendered string

- src/lib/components/base/tooltip/Tooltip.stories.tsx
- src/lib/components/base/tooltip/Tooltip.tsx
- src/lib/components/base/tooltip/useTooltip.ts
- src/lib/components/project/ProjectIcon.tsx
- src/lib/mount.tsx
- tailwind.config.js
This adapts the docs from https://floating-ui.com/docs/tooltip and https://floating-ui.com/docs/floatingarrow and also pulled in the styles from sentry to get tooltips rendering. The api is a little different from sentry `<Tooltip title="trigger">content</Tooltip>` vs. `<Tooltip><TooltipTrigger>trigger</TooltipTrigger><TooltipContent>content</TooltipContent></Tooltip>`. I think the more verbose api will be fine, just have to include tooltips in more composite components like ProjectIcon and not so often use it in huge view-like things.
I then applied them to the `<ProjectIcon>` component, which looks like this when they're all active:
Along the way I had to add the `data-theme` to our `portalMount` div, but inside the storybook the tooltip gets mounted into the `body` inside the iframe, …
> feat: Create a Tooltip component and use it with ProjectIcon

- src/lib/components/base/tooltip/useTooltip.ts
Before the build was reporting:
```
rc/lib/components/base/tooltip/useTooltip.ts:24:25 - error TS2742: The inferred type of 'useTooltip' cannot be named without a reference to '.pnpm/@floating-ui+react-dom@2.1.2_react-dom@18.3.1_react@18.3.1__react@18.3.1/node_modules/@floating-ui/react-dom'. This is likely not portable. A type annotation is necessary.
24 export default function useTooltip({
~~~~~~~~~~
```
So now we have explicit types on that function.
> fix: Improve types of useTooltip()

- src/lib/sentryApi/queryKeys.ts
`queryReferrer` should be always set, and not overridden. So we add it last to the object.
> fix: Disallow overriding referrer in queryOption helpers

- src/lib/index.ts
- src/lib/types/config.ts
- src/lib/utils/hydrateConfig.spec.ts
- src/lib/utils/hydrateConfig.ts
It `config.debug` was `undefined` at all times before this :(
Now it's a proper array and we can toggle different types of debug areas!
> fix: Return the debug field after fixing up the values

- src/lib/components/panels/feedback/FeedbackListItem.tsx
- src/lib/components/panels/feedback/FeedbackPanel.tsx
- src/lib/components/panels/issues/IssuesPanel.tsx
Currently, using the transaction name to show issues and feedbacks related to a page doesn't work well. We will show all results for now as this is needed for our demo pictures until we come up with a better solution.
Also fixed a typo
> ref: show all issues and feedbacks

- src/lib/components/panels/feedback/FeedbackPanel.tsx
Querying for feedbacks using `transaction` doesn't return any results, so we need to switch back to using `url`
> fix: Use url when querying for feedbacks

- .storybook/preview.tsx
- docs/conditional-script.md
- src/env/demo/App.tsx
- src/lib/components/Navigation.tsx
- src/lib/components/unauth/Login.tsx
- src/lib/context/ApiProxyContext.tsx
- src/lib/context/__mocks__/defaultConfig.ts
- src/lib/context/defaultConfig.ts
- src/lib/hooks/fetch/useSentryApi.ts
- src/lib/hooks/usePrevious.spec.ts
- src/lib/hooks/usePrevious.ts
- src/lib/sentryApi/urls.spec.ts
- src/lib/sentryApi/urls.ts
- src/lib/types/config.ts
- src/lib/utils/ApiProxy.spec.ts
- src/lib/utils/ApiProxy.ts
- src/lib/utils/hydrateConfig.spec.ts
Related to: https://github.com/getsentry/sentry/pull/81942
Changes:
- The `request-login` and `request-logout` messages are going over `iframe.contentWindow.postMessage()` now. The MessagePort is reserved for when the iframe is logged in and properly configured.
- When state _changes_ we dispose of any ports (would only been connected if we were previously logged in) and reload the iframe. This ensures that we get a new state told to us from the html file
- We've dropped the `sentryApiPath` config value, because the config endpoint (domain, region if needed, and this prefix) is set inside the iframe js scripts. The `fetch` command of the proxy can only make fetch requests to the sentry api now, not to other domains.
> feat: Iterate on ApiProxy to keep login/logout message off the MessageChannel

- package.json
- pnpm-lock.yaml
- src/lib/components/Navigation.tsx
https://headlessui.com/react/transition
Using `<Transition>` made it easier to have a nice fade in/out animation compared to the size change thing we were trying to do before. Also, it's adding much less to the bundle size. 
Bundle size numbers:
- framermotion added 107kb to the bundle
- i tried something called [auto-animate](https://auto-animate.formkit.com/#plugins), which added 7kb
- this `<Transition>` component added 6kb
While bundle size is not a primary concern for this dev focused build, it's a nice win.
> ref: Replace framer-motion with Transition from headlessui

- src/lib/sentryApi/urls.ts
- src/lib/types/config.ts
- src/lib/utils/hydrateConfig.spec.ts
- src/lib/utils/hydrateConfig.ts
In some places the `sentryOrigin` shows up in the UI, like the 'Connecting ...' message before login. In this case it's better to have set the default earlier because then it'll render to users and be guaranteed to be the same value that is actually trying to connect.
> feat: Set sentryOrigin default earlier so it appears in UI labels & everywhere

- src/lib/context/ApiProxyContext.tsx
- src/lib/types/config.ts
- src/lib/utils/hydrateConfig.spec.ts
- src/lib/utils/hydrateConfig.ts
Before the `0` was being put on the url and converted to a string, where python found it and turned it back into `"0"` which is now a truthy thing.
So we just need `""` to go into the url and be passed around.
> fix: Disable iframe logging

- .storybook/preview.tsx
This config is meant to conform to the internal Configuration type, it's not hydrated like `InitConfig` is.
> fix: Fix baseConfig in storybook preview.tsx

- .storybook/main.ts
- .storybook/preview.tsx
- src/lib/index.css
- src/lib/mount.tsx
- src/lib/utils/setColorScheme.tsx
Now in stories you can easily switch between light & dark mode using the built-in browser inspect tools
Light: 
Dark:
> ref: Refactor setColorScheme to reuse in stories

- src/env/demo/App.tsx
- src/lib/components/unauth/InvalidDomain.tsx
- src/lib/components/unauth/Login.tsx
- src/lib/components/unauth/MissingProject.tsx
Light mode always worked, but the link inside the pill was unreadable in dark mode. Fixed now.
**Before:**
| Dark |
| --- |
| <img width="712" alt="SCR-20241217-ssxw" src="https://github.com/user-attachments/assets/5d33b94f-38b5-4a84-8eba-1e37710099c5" />
**After:**
| Dark | Light |
| --- | --- |
| <img width="678" alt="SCR-20241217-stbs" src="https://github.com/user-attachments/assets/291844c5-7465-4854-b1ac-7845b9b88066" /> | <img width="686" alt="SCR-20241217-ssyw" src="https://github.com/user-attachments/assets/6728915c-4c05-4695-94c9-fd1e3d7bda14" />
> fix: Fix ExternalLink colors within the UnauthPill in dark mode

- src/lib/components/unauth/InvalidDomain.tsx
This will let sentry know which domain you're trying to use, and show a message to help you save the correct thing into the settings page.
> feat(setup): Pass the host + port to sentry settings page when domain is invalid

- mock/flagd/Makefile
- mock/flagd/config/demo.flagd.json
- package.json
- pnpm-lock.yaml
- src/lib/adapters/OpenFeatureAdapter.ts
- src/lib/adapters/localStorage.ts
- src/lib/components/panels/featureFlags/FeatureFlagItem.tsx
- src/lib/index.ts
- src/lib/utils/localStorage.ts
In this PR i've added a makefile and config to be able to run https://flagd.dev/ doe dev purposes, in order to feed back into the the OpenFeature SDK and then through the adapter into the UI, and a new Adapter to consume those flags!
The OpenFeature adapter itself is kind of janky, there are no public methods in the OpenFeature SKD for getting 'all flag' info back out. The OpenFeature type interface is something like:
```
type Provider = {
evaluateFlag(...): Result
};
class OpenFeature {
constructor(provider: Provider)
evaluateFlag(name, default) { return this.provider.evaluateFlag(...); }
}
```
And each provider implements their own 'private' cache of flag data, in different formats, in order to evaluate it. What's beneficial to us though it that most client side providers use the …
> feat(flags): Create an initial, basic, OpenFeature adapter to read feature flags

- .husky/pre-push
This was previously running tests locally before each commit which takes time and is noticeably slow.
So i'm removing this as all tests will be run in CI and must pass before merging.
> chore: Remove pre-commit script and let tests run in CI only

- src/lib/components/base/tooltip/Tooltip.tsx
Its a button because its focusable and keyboard accessible and stuff, but not clickable. So the cursor should reflect that.
Fixes #202
> fix: Set tooltip trigger cursor to `default`

- src/lib/components/panels/feedback/FeedbackListItem.tsx
- src/lib/components/panels/feedback/FeedbackPanel.tsx
- src/lib/components/panels/issues/IssueListItem.tsx
- src/lib/components/panels/issues/IssuesPanel.tsx
Hey team!
I noticed that some of the links that include a `?project=` actually use the `organizationSlug` instead of the `projectIdOrSlug`. Don't know if it's intentional, but I opened this PR anyway. Feel free to decline if it's intentional.
I noticed this because when I clicked on the Issues panel title link to take me to that project's issues, the project filter wasn't applied and it showed me issues for all of my projects instead. I noticed that we're actually sending the org slug as a project.
One more thing - I also noticed if we're using the project slug (ex. `flashcards`) instead of the project ID (ex. `4506045517135872`) the filter is also not applied - it only works if we use the project ID. I'm assuming it's a change in the platform that fails to apply the filter, but I'll open …
> fix: replacing organizationSlug with projectIdOrSlug where its needed

- src/lib/components/Navigation.tsx
- src/lib/components/base/Indicator.tsx
- src/lib/components/panels/featureFlags/FeatureFlagAdapterStub.ts
- src/lib/components/panels/featureFlags/FeatureFlagFilters.tsx
- src/lib/components/panels/featureFlags/FeatureFlagsPanel.tsx
- src/lib/components/panels/featureFlags/featureFlagsContext.tsx
- src/lib/context/Providers.tsx
Little indicators in the Nav and ontop of the segmented control to view overrides only:
Fixes https://github.com/getsentry/sentry/issues/86991
> feat(toolbar): Indicate when a FF override is in place

- src/lib/utils/transactionToSearchTerm.spec.ts
- src/lib/utils/transactionToSearchTerm.ts
https://svelte.dev/docs/kit/advanced-routing\#Matching
sveltekit routes can use matches like these:
```
src/routes/[...catchall]/+page.svelte
src/routes/[[a=x]]/+page.svelte
src/routes/[b]/+page.svelte
src/routes/foo-[c]/+page.svelte
src/routes/foo-abc/+page.svelte
```
We support all except `src/routes/foo-[c]/` now.
> fix: Support Sveltekit optional params in transaction names

- src/lib/components/panels/feedback/FeedbackListItem.tsx
Followup to https://github.com/getsentry/sentry/pull/90133
> feat(feedback): Display the crash report icon for django-endpoint feedbacks

- src/lib/components/layouts/CenterLayout.tsx
- src/lib/components/unauth/UnauthPill.tsx
The children of `<MainArea>` (which are all `<UnauthPill>` components) should accept pointer events, but since those divs are translated down from the actual `<MainArea>` we can remove pointer events from the main area itself. Because of the `translate-y` css, the main area is effectively 'empty space' on the page, used for aria correctness.
> fix: CenterLayout.MainArea should not capture mouse events, 

- src/lib/components/DragDropPositionSurface.tsx
- src/lib/components/Navigation.tsx
- src/lib/components/layouts/EdgeLayout.tsx
- src/lib/components/unauth/UnauthPill.tsx
- src/lib/context/MousePositionContext.tsx
**Updated labels and tooltips**
**Before**
The mouse-position stuff in here also fixes and issue where it would collapse while drag+drop was happening, and it looked a bit weird.
> feat: Iterate on expand/collapse labels, and keep expanded during drag+drop
